@startuml classDiagram

package db_handler {
    class DbHandler {
        -dbFile:String
        -apiKey:String
        +__init__()
        +add_isin()
        +add_symbol()
        +get_all(filter)
        +get_watchlist(filter)
        +get_entry(isin, filter)
        +update_all()
        +update_watchlist()
        +update_entry(isin)
        +set_watchlist(isin, state)
    }
}

package yasp_xls {
    class YaspXls{
        +update_all()
        +update_watchlist()
        +update_profiles()
    }
}

package yasp_ui {
    class YaspUi {
        +update_all()
        +update_watchlist()
        +safe_watchlist()
        +show_profiles()
    }
}

package user_def_link {
    class user_def_link <<functions>> {
        +get_chart_link(isin):string
        +get_trading_link(isin):string
    }
}

YaspXls --> DbHandler : uses
YaspUi --> DbHandler : uses
DbHandler --> user_def_link : calls

@enduml